services:

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # docker-entrypoint-initdb.d will only work when your data dictionary is empty. So if you have volumes, be sure to delete them docker-compose down --volumes
      # - ./movie-app/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./backend/.env
    # ports:
    #  - 5432:5432

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    # command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
    postgres_data:
