services:

  db:
    container_name: db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env

  server:
    container_name: phresh
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    # command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
    postgres_data:
